name: Feature Request
description: Suggest an idea for advanced peripherals
body:
  - type: textarea
    attributes:
      label: Describe your idea
      description: A clear and detailed description of your idea
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered if any
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: input
    attributes:
      label: Linked Issues
